version: 2
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/sgaunet/jwt-cli/cmd.version={{.Version}}
      - -X github.com/sgaunet/jwt-cli/cmd.commit={{.Commit}}
      - -X github.com/sgaunet/jwt-cli/cmd.buildDate={{.Date}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    id: lin
    # hooks:
    #   post:
    #     - upx "{{ .Path }}"

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    formats: ["binary"]

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - name: jwt-cli
    homepage: 'https://github.com/sgaunet/jwt-cli'
    description: 'CLI tool for encoding and decoding JWT tokens'
    directory: Casks
    binaries:
      - jwt-cli
    commit_author:
      name: sgaunet
      email: 1552102+sgaunet@users.noreply.github.com
    repository:
      owner: sgaunet
      name: homebrew-tools
      # Token with 'repo' scope is required for pushing to a different repository
      token: '{{ .Env.HOMEBREW_TAP_TOKEN }}'
    url:
      template: 'https://github.com/sgaunet/jwt-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}'


dockers_v2:
  # https://goreleaser.com/customization/dockers_v2/
  - id: jwt-cli
    dockerfile: Dockerfile
    images:
      - "ghcr.io/sgaunet/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm/v6
      - linux/arm/v7
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
