# https://taskfile.dev
version: '3'
vars:
  BINFILE: jwt-cli

tasks:
  default:
    cmds:
      - CGO_ENABLED=0 go build .
      # - upx -q {{.BINFILE}}
    # silent: true
    method: checksum
    generates:
      - "{{.BINFILE}}"

  install:
    cmds:
      - go get golang.org/x/tools/cmd/godoc

  doc:
    cmds:
      - echo http://localhost:6060
      - godoc -http=:6060
  
  snapshot:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot
    
  release:
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean

  tests:
    dir: tests
    cmds:
      - venom run testsuite.yml --output-dir="log" --stop-on-failure
