name: linter

on:
  push:

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      - name: Run linter
        shell: /usr/bin/bash {0}
        run: |
          task lint
